"""Mutable state containers used by the inference engine across timesteps."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass
class BufferState:
    """Stores raw buffer values keyed by semantic names.

    The state object is deliberately lightweight so the higher-level
    ``BufferManager`` can expose a small dictionary-like API while still making
    the ownership of mutable inference state explicit.
    """

    values: dict[str, Any] = field(default_factory=dict)


class BufferManager:
    """Owns cross-step inference buffers such as time step and action history."""

    def __init__(self) -> None:
        """Creates an empty buffer registry."""
        self.state = BufferState()

    def reset(self) -> None:
        """Clears all buffered values.

        This is typically called when a new episode starts and no previous
        inference context should leak into the next rollout.
        """
        self.state.values.clear()

    def get(self, name: str, default=None):
        """Returns a buffered value by name.

        Args:
            name: Semantic key such as ``"time_step"`` or ``"action"``.
            default: Value returned when the key does not exist.

        Returns:
            The stored value if present, otherwise ``default``.
        """
        return self.state.values.get(name, default)

    def set(self, name: str, value) -> None:
        """Stores or overwrites one buffered value."""
        self.state.values[name] = value

    def update(self, updates: dict[str, Any]) -> None:
        """Applies a batch update generated by one inference step."""
        self.state.values.update(updates)
